config/routes.rb
Rails.application.routes.draw do

  root "articles#index"
  
  get "/articles" => "articles#index", as: "article_index"

  get "/articles/new" => "articles#new", as: "article_new"
  
  post "/articles" => "articles#create", as: "article_create"

  get '/articles/edit/:id' => 'articles#edit', as: 'article_edit'

  post '/articles/:id' => 'articles#update', as: 'article_update'

   

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
   validates :name,  presence: true, 
                     uniqueness: true
   validates :body,  presence: true, 
                     length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to article_index_path
    else
      render :new
    end  
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to article_index_path
    else
      render :edit
    end 
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to article_index_path
  end

  private
  def article_params
    params.require(:article).permit(:name, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Blog MU Edit</h1>

<%= form_with scope: :article, url: article_update_path, local: true do |f| %>

<p>
   <% if @article.errors.any? %>
      <ul>
         <% @article.errors.full_messages.each do |message| %>
            <li> <%= message %> </li>
         <% end %>
      </ul>
   <% end %>
</p>

<p>
   <%= f.label :name %>
   <br/>
   <%= f.text_field :name %>
</p>

<p>
<%= f.label :body %>
<br/>
<%= f.text_field :body %>
</p>

<p>
<%= f.submit %>
</p>

<% end %>

<%= link_to 'Back to Index', article_index_path %>

app/views/articles/index.html.erb
<h1>Blog MU Index</h1>

<table>

   <thead>
      <tr>
         <th>ID</th>
         <th>Name</th>
         <th>Body</th>
         <th>Edit</th>
      </tr>
   </thead>

   <tbody>
      <% @articles.each do |article| %>
      <tr>
         <td><%= article.id %></td>
         <td><%= article.name %></td>
         <td><%= article.body %></td>
         <td> <%= link_to 'Edit', article_edit_path(article.id) %> </td>
         
      </tr>
      <% end %>
   </tbody>

</table>

<%= link_to 'New Article', article_new_path %>

app/views/articles/new.html.erb
<h1>Blog MU New</h1>

<%= form_with scope: :article, url: article_create_path, local: true do |f| %>

<p>
   <% if @article.errors.any? %>
      
         <% @article.errors.full_messages.each do |message| %>
            <p> <%= message %> </p>
         <% end %>
      
   <% end %>
</p>

<p>
   <%= f.label :name %>
   <br/>
   <%= f.text_field :name %>
</p>

<p>
<%= f.label :body %>
<br/>
<%= f.text_field :body %>
</p>

<p>
<%= f.submit %>
</p>

<% end %>

<%= link_to 'Back to Index', article_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>